// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { env } from '@repo/env'
import { defineConfig } from 'prisma/config'

export default defineConfig({
  schema: 'prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'bun run src/seed.ts'
  },
  datasource: {
    url: env.DATABASE_URL
  }
})
