// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { env } from '@repo/env'
import { defineConfig } from 'prisma/config'

export default defineConfig({
  schema: 'prisma',
  // No `seed` here on purpose: seeding needs @repo/api (Better Auth), and
  // @repo/db must not depend on it. Run `bun run db:seed` (apps/backend).
  migrations: {
    path: 'prisma/migrations'
  },
  datasource: {
    url: env.DATABASE_URL
  }
})
